---
apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  name: cluster-group-upgrades-operator.v0.0.0
  namespace: placeholder
spec:
  relatedImages:
    - image: quay.io/openshift-kni/cluster-group-upgrades-operator-recovery:0.0.3
      name: recovery
